-- SQLite
CREATE TABLE IF NOT EXISTS TeamViewerIDS(
    HostName TEXT NOT NULL PRIMARY KEY,
    TeamViewerID TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS HWIWorkstationCache(
    AssetTag TEXT NOT NULL PRIMARY KEY,
    HWID TEXT NOT NULL
);

